config/routes.rb
Rails.application.routes.draw do
  root to: 'payments#index'
  resources :payments
  get 'search/search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ApplicationRecord

    ESTADO = ["Procesando", "Aprobado", "Rechazado"]


end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]


  def index
    @start_date = params[:start].try(:to_date) || 30.days.ago.to_date
    @end_date = params[:end].try(:to_date) || Date.current
    range = (@start_date..@end_date)

    @payment = Payment.new
    @payments = Payment.where(created_at: range).paginate(page: params[:page], per_page: 10).order(created_at: :desc).all
  end

  def new
    @payment = Payment.new
  end


  def edit
  end

  def create
    @payment = Payment.new(payment_params)
    respond_to do |format|
      if @payment.save
        format.json { render :index, status: :created, location: @payment}
        format.js
      else
        format.json { render json: @payment.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @payment.errors, status: :unprocessable_entity }
        format.js { render :edit}
      end
    end
  end

  def destroy
    @payment.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private
    def set_payment
      @payment = Payment.find(params[:id])
    end

    def payment_params
      params.require(:payment).permit(:deudor, :numfact, :pay, :estado, :monto_total)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def search
        word = "%#{params[:word]}%"
        @payments = Payment.where("deudor LIKE ? OR id LIKE ? OR estado LIKE ?", word,word,word)
        respond_to do |format|
            format.json { render json: @payments }
            format.js
        end
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_date(created_at)
        l created_at, format: '%m-%d-%Y'
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pays</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600;700&display=swap" rel="stylesheet">    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_header.html.erb
<div class="row my-2 py-2 ">
  <div class="col bg-transparent container-margin">
    <h5 class="" id="title_h5">Anticipar</h5>
  </div>
</div>

  <div class="row py-2 mb-4 bg-white">
    <div class="col container-margin">

      <h4 class="float-left align-middle" id="title_h1">Cartola de Anticipos</h1>
      <%= link_to new_payment_path, {remote: true, class:'btn btn-primary align-middle float-right', id:'añadir-payment-btn'} do %>
        Anticipar Factura
      <% end %>
        
    </div>
  </div>
  <div class="container-margin">

    <ul class="nav nav-tabs mt-4" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Últimos Anticipos</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Simular Anticipos</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Mis Deudores</a>
      </li>
    </ul>
  </div>
  

 <div class="row mt-3 pt-3 padding-bottom ml-4">
   

    <div class="col form-inline">
      <div class="form-group">
        <%= form_tag '/search/search', method: :get, remote: true, id: 'search-form' do %>
        <%= text_field_tag("word", value = nil, options = { placeholder:' Buscar...', class:'form-control search_input mr-3'} ) %>
        <% end %>
        <input type="text" id="daterange" class="form-control search_input" placeholder="Ordenar"/>
      </div>
     
    </div>
  </div>

app/views/partials/_result.html.erb
<div class="row my-2 p-2">
    <div class="col">
        <%= link_to 'Home', root_path, class:"btn btn-light float-right"  %>

        <h5 class="float-left text-secondary">Resultados</h5>
    </div>
  </div>
  <div class="row shadow-sm p-2">
    <div class="col">

      <h4 class="float-left">Resultados de Anticipos</h1>
    </div>
  </div>

 <div class="row py-4">
   

    <div class="col form-inline">
      <div class="form-group">
        <%= form_tag "/search" do %>
        <%= text_field_tag("termino", value = nil, options = { placeholder:' Deudor o ID', class:'fa form-control mr-2'}) %>
        <% end %>
      </div>
     
    </div>
  </div>

app/views/partials/_table.html.erb
<table id="tablaPrepayments" class="table table-borderless" width="100">
      
    <thead>
        <tr>
            <th>ID</th>
            <th>Deudor</th>
            <th>Fecha</th>
            <th>N° Facturas</th>
            <th>% Anticipo</th>
            <th>Monto Final</th>
            <th>Estado</th>
        </tr>
    </thead>
    <tbody id="tablaPayments">
      <%= render @payments%>
    </tbody>

  </table>

app/views/payments/_form.html.erb
<%= form_for @payment, remote: true do |f| %>
    <div class="form-group">
        <h4 class="control-label">Datos de los anticipos</h4>
    </div>
    <div class="item form-group">
        <%= f.label :deudor, "Nombre del deudor: " %>
        <div class="input-group">
          <%= f.text_field :deudor, {:class=> "form-control", :placeholder=>"Introduzca el deudor..."} %>        
          
        </div>
    </div>
    <div class="item form-group">
        <%= f.label :numfact, "Numero de factura a anticipar: " %>
        <div class="input-group">
          <%= f.number_field :numfact, {:class=> "form-control", :placeholder=>"Introduzca el N° factura..."} %>        
         
        </div>
    </div>
    <div class="item form-group">
        <%= f.label :pay, "Porcentaje de anticipo: " %>
        <div class="input-group">
          <%= f.number_field :pay, {:class=> "form-control", :placeholder=>"Introduzca el porcentaje de anticipo..."} %> %        
         
        </div>
    </div>
    <div class="item form-group">
        <%= f.label "Monto total" %>
        <div class="input-group">
        <%= f.number_field :monto_total, {:class=> "form-control"} %>        
        </div>
    </div>
    <div class="form-group">
        <%= f.label :estado, "Selecciona un estado..." %>
          <%= f.select :estado, Payment::ESTADO, {:class=> "form-control", :placeholder=>"Seleccione un estado..."} %>
    </div>

    <div class="actions col-md-9 col-sm-9 col-xs-12 col-md-offset-3 float-right">
        <%= f.submit 'Guardar Anticipo', :class => "btn btn-primary"%>
    </div>  

<% end %>

app/views/payments/_modal_estado.html.erb
<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Editar Anticipo</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= render 'form' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary">Guardar</button>
        </div>
      </div>
    </div>
  </div>

app/views/payments/_modal_payments.html.erb
<div class="modal fade" id="modalPayments" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="modal-payments-title">Nuevo Anticipo</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="modal-body-payments">
            <%= render 'form' %>
        </div>
    
      </div>
    </div>
  </div>

app/views/payments/_payment.html.erb

<tr id="payment_<%= payment.id %>" class="row_payments bg-white">
    <td class="align-middle text-table"><a class="link" data-toggle="modal" data-target="#<%= payment.id.to_words.delete(' ') %>"> #<%= payment.id %></a></td>
    <td class="align-middle text-table"><a class="link" data-toggle="modal" data-target="#<%= payment.id.to_words.delete(' ') %>"><%= payment.deudor.capitalize %></a></td>
    <td class="align-middle text-table"><%= payment.created_at.strftime("%d-%m-%Y") %></td>
    <td class="align-middle text-table"><%= payment.numfact %></td>
    <td class="align-middle text-table"><%= payment.pay %> %</td>
    <td class="align-middle text-table"><% if payment.monto_total.present?%>$<% end%> <%= number_with_delimiter(payment.monto_total, :delimiter => '.') %></td>
    <td class="align-middle">
      <% if payment.estado === "Procesando" %>
        <div class="badge badge-warning">
          <%= payment.estado %>
        </div>
      <% elsif payment.estado === "Aprobado" %>
        <div class="badge badge-success">
          <%= payment.estado %>
        </div>
      <% else %>
        <div class="badge badge-danger">
          <%= payment.estado %>
        </div>
    <% end %>
    </td>
    <td class="align-middle">
      <div class="dropdown dropleft">
          
          <button class="btn btn-link dots_menu btn-lg" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
            </svg>
        </button>
          <div class="dropdown-menu">
            <%= link_to 'Modificar', edit_payment_path(payment), html_options = {class: "dropdown-item", data_target: "#modificarModel", data_toggle: "modal", remote: true} %>
              <%= link_to 'Eliminar', payment, remote: true, method: :delete, data: { confirm: "Estás seguro de eliminar el anticipo de #{payment.deudor}?" }, class: "dropdown-item" %>
          </div>
        </div>
    </td>
</tr>

<div class="modal fade" id="<%= payment.id.to_words.delete(' ') %>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Estado de Solicitud #<%= payment.id %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="pay_<%= payment.id %>" class="card <% if payment.estado === 'Procesando' %> border-warning
          <% elsif payment.estado === 'Aprobado' %>
          border-success
          <% else %>
          border-danger
          <% end %> shadow-sm mb-3 py-3">
          <div class="card-body text-primary">
              <h6 class="text-dark text-justify">
              <ul class="list-group">
                  <li class="list-group-item mx-3">
                    Nombre Deudor: <%= payment.deudor.capitalize%>
                  </li>
                  <li class="list-group-item mx-3">
                  Estado: <span class="badge <% if payment.estado === 'Procesando' %>
                      badge-warning
                      <% elsif payment.estado === 'Aprobado' %>
                      badge-success
                      <% else %>
                      badge-danger
                      <% end %>"><%= payment.estado %></span>
                  </li>
                  <li class="list-group-item mx-3">
                  Fecha: <%= payment.created_at.strftime("%d-%m-%Y")%>
                  </li>
                  <li class="list-group-item mx-3">
                  Número de Facturas: <%= payment.numfact %>
                  </li>
                  <li class="list-group-item mx-3">
                  Monto de Facturas: <%= number_with_delimiter(payment.monto_total, :delimiter => '.')%>
                  </li>
                  <li class="list-group-item mx-3">
                  <button class="btn btn-primary">Chat con Ejecutivo</button>
                  </li>
                  <li class="list-group-item mx-3">
                  <button class="btn btn-outline-primary">Ver Detalles</button>
                  </li>
              </ul>
              </h6>
              </div>
          </div>
      </div>
     
    </div>
  </div>
</div>

app/views/payments/_show.html.erb

<% @payments.each do |pay| %>
<div class="modal fade" id="<%= pay.id.to_s%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Estado de Solicitud #<%= pay.id %></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <div id="pay_<%= pay.id %>" class="card <% if pay.estado === 'Procesando' %> border-warning
            <% elsif pay.estado === 'Aprobado' %>
            border-success
            <% else %>
            border-danger
            <% end %> shadow-sm mb-3 py-3">
            <div class="card-body text-primary">
                <h6 class="text-dark text-justify">
                <ul class="nav justify-content-center align-items-center">
                    <li class="nav-item mx-3">
                    Estado: <span class="badge <% if pay.estado === 'Procesando' %>
                        badge-warning
                        <% elsif pay.estado === 'Aprobado' %>
                        badge-success
                        <% else %>
                        badge-danger
                        <% end %>"><%= pay.estado %></span>
                    </li>
                    <li class="nav-item mx-3">
                    Fecha: <%= pay.created_at.strftime("%d-%m-%Y")%>
                    </li>
                    <li class="nav-item mx-3">
                    Número de Facturas: <%= pay.numfact %>
                    </li>
                    <li class="nav-item mx-3">
                    Monto de Facturas: <%= number_with_delimiter(pay.monto_total, :delimiter => '.')%>
                    </li>
                    <li class="nav-item mx-3">
                    <button class="btn btn-primary">Chat con Ejecutivo</button>
                    </li>
                    <li class="nav-item mx-3">
                    <button class="btn btn-outline-primary">Ver Detalles</button>
                    </li>
                </ul>
                </h6>
                </div>
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  

<% end %>

app/views/payments/create.js.erb
$('#modalPayments').modal('toggle');
$('#tablaPayments').prepend(
    '<tr id="payment_<%= @payment.id %>" class="row_payments" ><td class="align-middle text-table"><a class="link" data-toggle="modal" data-target="#<%= @payment.id.to_words.delete(' ') %>"> #<%= @payment.id %></a></td><td class="align-middle text-table"><a class="link" data-toggle="modal" data-target="#<%= @payment.id.to_words.delete(' ') %>"><%= @payment.deudor.capitalize %></a></td><td class="align-middle"><%= @payment.created_at.strftime("%d-%m-%Y") %></td><td class="align-middle"><%= @payment.numfact %></td><td class="align-middle"><%= @payment.pay %></td><td class="align-middle"><%= number_with_delimiter(@payment.monto_total, :delimiter => '.') %></td><td class="align-middle"><% if @payment.estado === "Procesando" %><div class="badge badge-warning"><%= @payment.estado %></div><% elsif @payment.estado === "Aprobado" %><div class="badge badge-success"><%= @payment.estado %></div><% else %><div class="badge badge-danger"><%= @payment.estado %></div><% end %></td><td class="align-middle"><div class="dropdown dropleft"><button class="btn btn-link dots_menu btn-lg" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/></svg></button><div class="dropdown-menu"><%= link_to 'Modificar', edit_payment_path(@payment), html_options = {class: "dropdown-item", data_target: "#modificarModel", data_toggle: "modal", remote: true} %><%= link_to 'Eliminar', @payment, remote: true, method: :delete, data: { confirm: "Estas seguro de eliminar el anticipo de #{@payment.deudor}?" }, class: "dropdown-item" %></div></div></td></tr>'
);

app/views/payments/destroy.js.erb
$('#payment_<%= @payment.id %>').fadeOut();

app/views/payments/edit.js.erb
// Agrega un titulo al dialogo
$('#modal-payments-title').html("Editar Información");

// Render un nuevo formulario
$('#modal-body-payments').html('<%= j render "form" %>');

// Muestra un dialogo dnamico
$('#modalPayments').modal("show");

  

app/views/payments/index.html.erb
<div class="container-fluid bg-light">
  <%= render './partials/header'%>
<div class="container-margin">
  <div class="tab-content bg-light-grey" id="myTabContent">
    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
      

      <table id="tablaPrepayments" class="table table-borderless" width="100">
      
        <thead>
            <tr>
                <th>ID</th>
                <th>Deudor</th>
                <th>Fecha</th>
                <th>N° Facturas</th>
                <th>% Anticipo</th>
                <th>Monto Final</th>
                <th>Estado</th>
            </tr>
        </thead>
        <tbody id="tablaPayments">

          <%= render @payments%>
        </tbody>
    
      </table>
     
  
    <%= will_paginate @payments, list_classes: %w(pagination justify-content-center), previous_label: '&laquo;', :next_label => '&raquo;' , renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
    <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>
    <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
  </div>
</div>
</div>

  
<div class="modal fade" id="modalPayments" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-payments-title">Nuevo Anticipo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body-payments">
          <%= render 'form' %>
      </div>
  
    </div>
  </div>
</div>


<%= form_tag root_path, method: :get do %>
  <%= hidden_field_tag :start %>
  <%= hidden_field_tag :end %>
<% end %>


<script>
  var ranges = {
           'Hoy': ["<%= format_date(Date.current)%>"],
           'Últimos 7 Días': ["<%= format_date(Date.current - 7)%>", "<%= format_date(Date.current)%>"],
           'Últimos 30 Días': ["<%= format_date(Date.current - 30)%>", "<%= format_date(Date.current)%>"],
           'Este Mes': ["<%= format_date(Date.current.beginning_of_month)%>", "<%= format_date(Date.current)%>"],
           'Último Mes': ["<%= format_date(1.month.ago.beginning_of_month)%>", "<%= format_date(1.month.ago.end_of_month)%>"],
           'Último Año': ["<%= format_date(Date.current.beginning_of_year)%>", "<%= format_date(Date.current)%>"]
        };
  $(function() {
    $('#daterange').daterangepicker({
      startDate: moment("<%= l @start_date, format: '%Y-%m-%d' %>"),
      endDate: moment("<%= l @end_date, format: '%Y-%m-%d' %>"),
      ranges: ranges,
      alwaysShowCalendars: true
      
    }, function(start, end, label) {
      $("#start").val(start.format('YYYY-MM-DD'));
      $("#end").val(end.format('YYYY-MM-DD'));

      $("form").submit();
    });
  });
</script>


<script>
  function mostrarCartas() {
    document.getElementById('pay_<%= @payment.id %>').style.display = 'block';
  }

</script>

app/views/payments/new.js.erb
// Agrega un titulo al dialogo
$('#modal-payments-title').html("Nuevo Anticipo");

// Render un nuevo formulario
$('.modal-body-payments').html('<%= j render("form") %>');

// Muestra un dialogo dnamico
$('#modalPayments').modal("show");

  

app/views/payments/results.html.erb
<div class="container bg-light">
    <%= render './partials/result'%>

<table id="tablaPrepayments" class="table table-borderless" width="100">
    <thead>
        <tr>
            <th>ID</th>
            <th>Deudor</th>
            <th>Fecha</th>
            <th>N° Facturas</th>
            <th>% Anticipo</th>
            <th>Monto Final</th>
            <th>Estado</th>
        </tr>
    </thead>
    <tbody>
        <%= render @payments %>
    </tbody>
</table>
</div>


<%= render 'modal_payments' %>

app/views/payments/update.js.erb
$('#modalPayments').modal('toggle');
$('#payment_<%= @payment.id %>').replaceWith(
    '<tr id="payment_<%= @payment.id %>" class="row_payments" ><td class="align-middle text-table"><a class="link" data-toggle="modal" data-target="#<%= @payment.id.to_words.delete(' ') %>"> #<%= @payment.id %></a></td><td class="align-middle text-table"><a class="link" data-toggle="modal" data-target="#<%= @payment.id.to_words.delete(' ') %>"><%= @payment.deudor.capitalize %></a></td><td class="align-middle"><%= @payment.created_at.strftime("%d-%m-%Y") %></td><td class="align-middle"><%= @payment.numfact %></td><td class="align-middle"><%= @payment.pay %></td><td class="align-middle"><%= number_with_delimiter(@payment.monto_total, :delimiter => '.') %></td><td class="align-middle"><% if @payment.estado === "Procesando" %><div class="badge badge-warning"><%= @payment.estado %></div><% elsif @payment.estado === "Aprobado" %><div class="badge badge-success"><%= @payment.estado %></div><% else %><div class="badge badge-danger"><%= @payment.estado %></div><% end %></td><td class="align-middle"><div class="dropdown dropleft"><button class="btn btn-link dots_menu btn-lg" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-three-dots-vertical" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M9.5 13a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0zm0-5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/></svg></button><div class="dropdown-menu"><%= link_to 'Modificar', edit_payment_path(@payment), html_options = {class: "dropdown-item", data_target: "#modificarModel", data_toggle: "modal", remote: true} %><%= link_to 'Eliminar', @payment, remote: true, method: :delete, data: { confirm: "Estas seguro de eliminar el anticipo de #{@payment.deudor}?" }, class: "dropdown-item" %></div></div></td></tr>'
);

app/views/search/results.html.erb
<div class="container-fluid bg-light">
    <%= render './partials/header'%>

<table id="tablaPrepayments" class="table table-borderless" width="100">
    <thead>
        <tr>
            <th>ID</th>
            <th>Deudor</th>
            <th>Fecha</th>
            <th>N° Facturas</th>
            <th>% Anticipo</th>
            <th>Monto Final</th>
            <th>Estado</th>
        </tr>
    </thead>
    <tbody>
        <%= render @payments %>
    </tbody>
</table>
</div>



app/views/search/search.js.erb
$("#tablaPayments").html("<%= j render @payments %>")